[anantbuy]
anantbuy ansible_host=13.127.26.241 prometheus_target_ip=10.0.1.49

[devsecops]
devsecops ansible_host=3.6.38.196 prometheus_target_ip=10.0.1.47

[anantx]
anantx ansible_host=3.6.92.223 prometheus_target_ip=10.0.1.135

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/vibhor-key.pem